import React from "react";
import { Link } from "react-router-dom";
import MarketingShell from "@/components/marketing/MarketingShell";
import { AlertCircle, ArrowRight, Mail } from "lucide-react";
import { createPageUrl } from "@/utils";

const LAST_UPDATED = "May 2026";

const SECTIONS = [
  {
    id: "service-scope",
    title: "1. Service scope and nature",
    content: [
      {
        heading: "What HealthFlux is",
        text: "HealthFlux is a personal health operating system that helps individuals and families organize health records, track vitals, manage medications, and access AI-powered health insights.",
      },
      {
        heading: "What HealthFlux is not",
        list: [
          "HealthFlux is not a licensed medical provider and does not provide medical diagnosis, treatment, or clinical advice",
          "AI-generated content (summaries, reports, insights, coaching) is for informational purposes only and should not replace professional medical judgment",
          "HealthFlux is not an emergency service — do not use the app in a medical emergency",
          "HealthFlux does not provide pharmacy, dispensing, or prescription services",
        ],
      },
      {
        heading: "Disclaimer",
        text: "Always consult a qualified healthcare professional before making decisions based on information in HealthFlux. AI health insights are educational and may not reflect your actual clinical situation.",
        highlight: true,
      },
    ],
  },
  {
    id: "accounts",
    title: "2. Accounts and profiles",
    content: [
      {
        heading: "Account creation",
        text: "You must be 18 years of age or older to create a HealthFlux account. By creating an account, you confirm that the information you provide is accurate and that you are authorized to manage any profiles you create for others.",
      },
      {
        heading: "Account security",
        text: "You are responsible for maintaining the confidentiality of your login credentials. You are responsible for all activity under your account. Notify us immediately if you suspect unauthorized access.",
      },
      {
        heading: "Family profiles and caregiver access",
        text: "You may create profiles for family members or dependents with their knowledge and consent (or on behalf of minors in your care). When granting caregiver access to others, you remain responsible for ensuring that access is appropriate and consensual.",
      },
    ],
  },
  {
    id: "acceptable-use",
    title: "3. Acceptable use",
    content: [
      {
        heading: "Permitted use",
        text: "HealthFlux is licensed for personal, non-commercial health management use for yourself and your immediate family members.",
      },
      {
        heading: "Prohibited activities",
        list: [
          "Sharing your account with people outside your household or care relationship",
          "Using HealthFlux to manage health records for patients in a clinical capacity without an enterprise agreement",
          "Attempting to extract, scrape, or systematically copy health data from other users",
          "Using the AI features to generate content intended to mislead or deceive others about health conditions",
          "Reverse engineering, decompiling, or attempting to extract source code",
          "Uploading malicious files or content designed to disrupt the service",
        ],
      },
    ],
  },
  {
    id: "ai-content",
    title: "4. AI features and generated content",
    content: [
      {
        heading: "Nature of AI outputs",
        text: "The AI assistant, health coach, health reports, drug interaction checks, skin assessments, and diet plans are generated by AI models using your profile data as context. These outputs are informational and educational — they do not constitute medical advice.",
      },
      {
        heading: "Accuracy and limitations",
        text: "AI-generated content may contain errors, omissions, or outdated information. HealthFlux does not guarantee the accuracy of any AI output. Always verify important health information with a qualified healthcare professional.",
      },
    ],
  },
  {
    id: "data-ownership",
    title: "5. Data ownership and intellectual property",
    content: [
      {
        heading: "Your data",
        text: "You own all health data you enter into HealthFlux. We do not claim ownership of your health records, documents, or personal information. Our Privacy Policy describes how we handle this data.",
      },
      {
        heading: "HealthFlux intellectual property",
        text: "The HealthFlux application, design, AI models, algorithms, documentation, and all associated intellectual property are owned by HealthFlux. Using the service does not grant you any intellectual property rights in HealthFlux.",
      },
    ],
  },
  {
    id: "subscriptions",
    title: "6. Subscriptions and payments",
    content: [
      {
        heading: "Billing",
        text: "Paid plans are billed monthly or annually as selected at checkout. Prices are in Indian Rupees (INR) unless otherwise stated.",
      },
      {
        heading: "Cancellation",
        text: "You may cancel your subscription at any time. Your access continues until the end of the current billing period. We do not provide prorated refunds for partial billing periods.",
      },
    ],
  },
  {
    id: "termination",
    title: "7. Termination and account deletion",
    content: [
      {
        heading: "Your right to delete",
        text: "You can delete your account at any time from Settings > Account > Delete Account. Deletion permanently removes your account and all associated data within 30 days.",
      },
      {
        heading: "Our right to terminate",
        text: "We may suspend or terminate accounts that violate these Terms, engage in harmful behavior, or where required by law. We will provide notice where possible.",
      },
    ],
  },
  {
    id: "liability",
    title: "8. Limitation of liability",
    content: [
      {
        text: "HealthFlux is provided \"as is\" without warranties of any kind. To the maximum extent permitted by law, HealthFlux shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the service, including but not limited to health decisions made based on AI-generated content.",
      },
    ],
  },
  {
    id: "changes",
    title: "9. Changes to these Terms",
    content: [
      {
        text: "We may update these Terms from time to time. We will notify you of material changes by email or in-app notification at least 14 days before they take effect. Continued use of HealthFlux after the effective date constitutes acceptance of the updated Terms.",
      },
    ],
  },
  {
    id: "governing-law",
    title: "10. Governing law",
    content: [
      {
        text: "These Terms are governed by the laws of India. Disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in India.",
      },
    ],
  },
];

function TermsSection({ section }) {
  return (
    <div id={section.id} className="scroll-mt-24">
      <h2 className="text-lg font-black mb-5" style={{ color: "#0f172a" }}>{section.title}</h2>
      <div className="space-y-4">
        {section.content.map((block, i) => (
          <div key={i} className={block.highlight ? "p-4 rounded-xl" : ""}
            style={block.highlight ? { background: "rgba(255,197,101,0.12)", border: "1px solid rgba(255,197,101,0.3)" } : {}}>
            {block.heading && (
              <h3 className="text-sm font-bold mb-2" style={{ color: block.highlight ? "#7a3d00" : "#0f172a" }}>
                {block.heading}
              </h3>
            )}
            {block.text && (
              <p className="text-sm leading-relaxed" style={{ color: block.highlight ? "#7a3d00" : "#475569" }}>
                {block.text}
              </p>
            )}
            {block.list && (
              <ul className="space-y-1.5 mt-1">
                {block.list.map(item => (
                  <li key={item} className="flex items-start gap-2 text-sm" style={{ color: "#475569" }}>
                    <span className="w-1.5 h-1.5 rounded-full mt-2 flex-shrink-0" style={{ background: "#94a3b8" }} />
                    {item}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}

export default function Terms() {
  return (
    <MarketingShell currentPage="Terms">
      {/* Hero */}
      <section className="py-16 px-6" style={{ background: "linear-gradient(135deg, #fafaf8 0%, #fff8f0 100%)" }}>
        <div className="max-w-3xl mx-auto">
          <span className="inline-block px-4 py-1.5 rounded-full text-xs font-black uppercase tracking-widest mb-6"
            style={{ background: "rgba(247,201,163,0.3)", color: "#7a3d00" }}>
            Terms of service
          </span>
          <h1 className="text-4xl md:text-5xl font-black mb-5 leading-tight" style={{ color: "#0f172a" }}>
            Clear terms for a health platform
          </h1>
          <p className="text-lg leading-relaxed mb-6" style={{ color: "#475569" }}>
            These terms govern your use of HealthFlux. We've written them clearly so you
            know exactly what you're agreeing to.
          </p>
          <div className="flex items-center gap-3">
            <p className="text-sm" style={{ color: "#94a3b8" }}>Last updated: {LAST_UPDATED}</p>
            <span style={{ color: "#e2e8f0" }}>·</span>
            <Link to={createPageUrl("Privacy")} className="text-sm font-medium" style={{ color: "#64748b" }}>
              Privacy Policy →
            </Link>
          </div>
        </div>
      </section>

      {/* Disclaimer banner */}
      <section className="px-6 py-5" style={{ background: "#fffbeb" }}>
        <div className="max-w-3xl mx-auto flex items-start gap-3">
          <AlertCircle size={18} className="flex-shrink-0 mt-0.5" style={{ color: "#d97706" }} />
          <p className="text-sm" style={{ color: "#92400e" }}>
            <strong>Important:</strong> HealthFlux is not a medical service. AI-generated health insights and reports are informational only and do not constitute medical advice. Always consult a qualified healthcare professional for medical decisions.
          </p>
        </div>
      </section>

      {/* Main content */}
      <section className="py-16 px-6" style={{ background: "#ffffff" }}>
        <div className="max-w-3xl mx-auto">
          {/* Table of contents */}
          <div className="p-6 rounded-2xl mb-12" style={{ background: "#fafaf8", border: "1px solid rgba(15,23,42,0.08)" }}>
            <p className="text-xs font-black uppercase tracking-widest mb-4" style={{ color: "#94a3b8" }}>Contents</p>
            <div className="grid sm:grid-cols-2 gap-2">
              {SECTIONS.map(s => (
                <a key={s.id} href={`#${s.id}`}
                  className="text-sm font-medium hover:opacity-70 transition-opacity"
                  style={{ color: "#0f172a" }}>
                  → {s.title}
                </a>
              ))}
            </div>
          </div>

          <div className="space-y-12 divide-y" style={{ divideColor: "rgba(15,23,42,0.06)" }}>
            {SECTIONS.map(s => (
              <div key={s.id} className="pt-12 first:pt-0">
                <TermsSection section={s} />
              </div>
            ))}
          </div>

          <div className="mt-14 p-6 rounded-2xl" style={{ background: "#fafaf8", border: "1px solid rgba(15,23,42,0.08)" }}>
            <div className="flex items-start gap-4">
              <div className="w-10 h-10 rounded-xl flex items-center justify-center flex-shrink-0"
                style={{ background: "rgba(215,245,118,0.3)" }}>
                <Mail size={18} style={{ color: "#5a7a00" }} />
              </div>
              <div>
                <h3 className="font-bold mb-1" style={{ color: "#0f172a" }}>Questions about these Terms</h3>
                <p className="text-sm mb-3" style={{ color: "#64748b" }}>
                  If you have questions about these Terms of Service, please contact us.
                </p>
                <a href="mailto:legal@healthflux.app" className="text-sm font-semibold" style={{ color: "#5a7a00" }}>
                  legal@healthflux.app
                </a>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Related links */}
      <section className="py-16 px-6" style={{ background: "#fafaf8" }}>
        <div className="max-w-3xl mx-auto">
          <h2 className="text-xl font-black mb-6" style={{ color: "#0f172a" }}>Related policies</h2>
          <div className="grid sm:grid-cols-3 gap-4">
            {[
              { label: "Privacy Policy", page: "Privacy", desc: "How we handle your health data" },
              { label: "Cookie Policy", page: "Cookies", desc: "How we use cookies and tracking" },
              { label: "Trust Center", page: "TrustCenter", desc: "Security and compliance overview" },
            ].map(({ label, page, desc }) => (
              <Link key={page} to={createPageUrl(page)}
                className="p-5 rounded-2xl flex flex-col gap-1.5 hover:shadow-sm transition-shadow"
                style={{ background: "#ffffff", border: "1px solid rgba(15,23,42,0.08)" }}>
                <span className="font-bold text-sm" style={{ color: "#0f172a" }}>{label}</span>
                <span className="text-xs" style={{ color: "#64748b" }}>{desc}</span>
                <ArrowRight size={12} className="mt-1" style={{ color: "#94a3b8" }} />
              </Link>
            ))}
          </div>
        </div>
      </section>
    </MarketingShell>
  );
}

const sections = [
  {
    id: "scope",
    eyebrow: "Section 01",
    title: "Scope of service",
    body: "HealthFlux is a personal health platform for records, reminders, AI summaries, and care coordination. It is not a replacement for licensed medical diagnosis or emergency care.",
  },
  {
    id: "accounts",
    eyebrow: "Section 02",
    title: "Accounts, profiles, and data responsibility",
    body: "Users are responsible for account security, profile accuracy, and appropriate use of shared family or caregiver access. Profile context should reflect the real person whose data is being managed.",
  },
  {
    id: "ai",
    eyebrow: "Section 03",
    title: "AI-generated content disclaimer",
    body: "AI assistant, OCR, reports, and summaries are informational. They may be incomplete or mistaken, and must not be treated as a substitute for qualified medical advice.",
  },
  {
    id: "limits",
    eyebrow: "Section 04",
    title: "Operational limits and acceptable use",
